apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices-demo
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - mailhog.yaml
  - user-service.yaml
  - catalog-service.yaml
  - cart-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - shipping-service.yaml
  - notification-service.yaml
  - gateway.yaml
  - frontend.yaml
