apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: microservices-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - mailhog.yaml
  - user-service.yaml
  - catalog-service.yaml
  - cart-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - notification-service.yaml
  - shipping-service.yaml
  - gateway.yaml
  - frontend.yaml
